package com.teach.model;
// Generated 2017-7-14 14:34:49 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * TpCourseware generated by hbm2java
 */
@Entity
@DynamicInsert(true)
@DynamicUpdate(true)
@Table(name = "TP_CoursewareRandom", schema = "dbo", catalog = "Task")
public class TpCoursewareRandom implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer id;
	
	@Column(name="lessonId")
	private int lessonId;
	
	@Column(name="randomNum")
	private int randomNum;

	public TpCoursewareRandom() {
		super();
	}

	public TpCoursewareRandom(Integer id, int lessonId, int randomNum) {
		super();
		this.id = id;
		this.lessonId = lessonId;
		this.randomNum = randomNum;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getLessonId() {
		return lessonId;
	}

	public void setLessonId(int lessonId) {
		this.lessonId = lessonId;
	}

	public int getRandomNum() {
		return randomNum;
	}

	public void setRandomNum(int randomNum) {
		this.randomNum = randomNum;
	}

	@Override
	public String toString() {
		return "TpCoursewareRandom [id=" + id + ", lessonId=" + lessonId + ", randomNum=" + randomNum + "]";
	}

}
