package com.teach.model;
// Generated 2017-7-14 14:34:49 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * TpCourseware generated by hbm2java
 */
@Entity
@DynamicInsert(true)
@DynamicUpdate(true)
@Table(name = "TP_Courseware", schema = "dbo", catalog = "Task")
public class TpCourseware implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private int lessonId;
	private String content;
	private String animation;
	private String aboveWords;
	private String thumbnail;
	private String lessonVideoUrl;
	private String memoirVideoUrl;
	private Integer oaId;
	private Date creatTime;
	private Date updateTime;
	private byte pptType;
	private String pageAboveWords;
	private String uploadPptName;
	private String teachCaseName;
	private String teachCaseContent;
	

	public TpCourseware() {
	}

	public TpCourseware(int lessonId) {
		this.lessonId = lessonId;
	}

	public TpCourseware(Integer id, int lessonId, String content, String animation, String aboveWords, String thumbnail,
			String lessonVideoUrl, String memoirVideoUrl, Integer oaId, Date creatTime, Date updateTime, byte pptType,
			String pageAboveWords, String uploadPptName) {
		super();
		this.id = id;
		this.lessonId = lessonId;
		this.content = content;
		this.animation = animation;
		this.aboveWords = aboveWords;
		this.thumbnail = thumbnail;
		this.lessonVideoUrl = lessonVideoUrl;
		this.memoirVideoUrl = memoirVideoUrl;
		this.oaId = oaId;
		this.creatTime = creatTime;
		this.updateTime = updateTime;
		this.pptType = pptType;
		this.pageAboveWords = pageAboveWords;
		this.uploadPptName = uploadPptName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "lessonId", nullable = false)
	public int getLessonId() {
		return this.lessonId;
	}

	public void setLessonId(int lessonId) {
		this.lessonId = lessonId;
	}

	@Column(name = "content")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "animation")
	public String getAnimation() {
		return this.animation;
	}

	public void setAnimation(String animation) {
		this.animation = animation;
	}

	@Column(name = "aboveWords")
	public String getAboveWords() {
		return this.aboveWords;
	}

	public void setAboveWords(String aboveWords) {
		this.aboveWords = aboveWords;
	}
	
	@Column(name = "thumbnail")
	public String getThumbnail() {
		return thumbnail;
	}
	
	public void setThumbnail(String thumbnail) {
		this.thumbnail = thumbnail;
	}

	@Column(name = "lessonVideoUrl")
	public String getLessonVideoUrl() {
		return this.lessonVideoUrl;
	}

	public void setLessonVideoUrl(String lessonVideoUrl) {
		this.lessonVideoUrl = lessonVideoUrl;
	}

	@Column(name = "memoirVideoUrl")
	public String getMemoirVideoUrl() {
		return this.memoirVideoUrl;
	}

	public void setMemoirVideoUrl(String memoirVideoUrl) {
		this.memoirVideoUrl = memoirVideoUrl;
	}

	@Column(name = "oaId")
	public Integer getOaId() {
		return this.oaId;
	}

	public void setOaId(Integer oaId) {
		this.oaId = oaId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creatTime", length = 23)
	public Date getCreatTime() {
		return this.creatTime;
	}

	public void setCreatTime(Date creatTime) {
		this.creatTime = creatTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateTime", length = 23)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
	
	@Column(name = "pptType")
	public byte getPptType() {
		return pptType;
	}
	
	public void setPptType(byte pptType) {
		this.pptType = pptType;
	}
	
	@Column(name = "pageAboveWords")
	public String getPageAboveWords() {
		return pageAboveWords;
	}

	public void setPageAboveWords(String pageAboveWords) {
		this.pageAboveWords = pageAboveWords;
	}

	@Column(name = "uploadPptName")
	public String getUploadPptName() {
		return uploadPptName;
	}

	public void setUploadPptName(String uploadPptName) {
		this.uploadPptName = uploadPptName;
	}

	@Column(name = "teachCaseName")
	public String getTeachCaseName() {
		return teachCaseName;
	}

	public void setTeachCaseName(String teachCaseName) {
		this.teachCaseName = teachCaseName;
	}

	@Column(name = "teachCaseContent")
	public String getTeachCaseContent() {
		return teachCaseContent;
	}

	public void setTeachCaseContent(String teachCaseContent) {
		this.teachCaseContent = teachCaseContent;
	}

	@Override
	public String toString() {
		return "TpCourseware [id=" + id + ", lessonId=" + lessonId + ", content=" + content + ", animation=" + animation
				+ ", aboveWords=" + aboveWords + ", thumbnail=" + thumbnail + ", lessonVideoUrl=" + lessonVideoUrl
				+ ", memoirVideoUrl=" + memoirVideoUrl + ", oaId=" + oaId + ", creatTime=" + creatTime + ", updateTime="
				+ updateTime + "]";
	}

}
