package com.teach.model;
// Generated 2017-7-14 14:34:49 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * TpFeedback generated by hbm2java
 */
@Entity
@DynamicInsert(true)
@DynamicUpdate(true)
@Table(name = "TP_Feedback", schema = "dbo", catalog = "Task")
public class TpFeedback implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private int oaId;
	private String content;
	private byte comment;
	private int lessonId;
	private Integer courceId;
	private Date createDate;

	public TpFeedback() {
	}

	public TpFeedback(int oaId, String content, byte comment, int lessonId) {
		this.oaId = oaId;
		this.content = content;
		this.comment = comment;
		this.lessonId = lessonId;
	}

	public TpFeedback(int oaId, String content, byte comment, int lessonId, Integer courceId, Date createDate) {
		this.oaId = oaId;
		this.content = content;
		this.comment = comment;
		this.lessonId = lessonId;
		this.courceId = courceId;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "OaId", nullable = false)
	public int getOaId() {
		return this.oaId;
	}

	public void setOaId(int oaId) {
		this.oaId = oaId;
	}

	@Column(name = "content", nullable = false)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "comment", nullable = false)
	public byte getComment() {
		return this.comment;
	}

	public void setComment(byte comment) {
		this.comment = comment;
	}

	@Column(name = "lessonId", nullable = false)
	public int getLessonId() {
		return this.lessonId;
	}

	public void setLessonId(int lessonId) {
		this.lessonId = lessonId;
	}

	@Column(name = "courceId")
	public Integer getCourceId() {
		return this.courceId;
	}

	public void setCourceId(Integer courceId) {
		this.courceId = courceId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createDate", length = 23)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
